---
title: Post-Election Reflection
author: Vivian Nguyen
date: '2022-11-22'
slug: []
categories: []
tags: []
---

This is blog post #9 (post-election) in a series of analytical posts about the 2022 midterms. This post is affiliated with Gov 1347: Election Analytics, a course at Harvard University in the Government department.

---
```{r setup, include = FALSE, message = FALSE}
# # Set up
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(janitor)
library(readr)
library(stargazer)
library(usmap)
library(rmapshaper)
library(sf)
library(insight)
library(scales)
library(packcircles)

# 
# expert_ratings <- read_csv("expert_rating.csv")
# historical_results <- read_csv("historical_results.csv")
# # df <- read_csv("econ_mid_genball_results.csv")
# d2022 <- read_csv("house_cands.csv")
# cook <- read_csv("cook.csv")
# inside <- read_csv("inside_elections.csv")
# 
# nat_model_data <- read_csv("nat_model_data.csv")
# poll_df <- read_csv("538_generic_ballot_averages_2018-2022.csv")
```

# Overview
This week, I am revisiting my final models and predictions from [week 8](https://vivian-1372.github.io/Election-Analytics/post/2022-11-07-final-prediction/) and reflecting on how they performed, and speculating about why, now that we're about 2 weeks post-Election Day now.

# My Final Model and Predictions
## National Model
My national modeling addressed two main goals: predicting the 2022 House incumbent party two-party vote share and predicting the 2022 House incumbent party seat count. My main model consisted of a linear regression built off of 4 predictors (GDP absolute growth, generic ballot support for the House incumbent party, whether or not it was a midterm year for the incumbent/President's party, and the congressional approval rate). To achieve the two goals, I swapped out the response variable as needed. 

Ultimately, I predicted that the House imcumbent party (Democrats this year) would earn 48.56% (47.36, 49.83) of the national two-party vote share and 209 (198, 221) seats. 
## District-Level Models
My district-level modeling also consisted of two main goals: predict the vote share of the Democratic candidate in competitive districts and predict the vote share of the Democratic candidate in "non-competitive" districts. My approach was to build competitive linear regression models using average expert ratings of those races in addition to  candidate incumbency status, and to build non-competitive ones using the last Democratic canddiate's vote share as well as the current candidate's incumbency.  



## Accuracy 
A description of the accuracy of the model(s), including any apparent patterns in the accuracy.  Graphics should be used here.

## Sources of Inaccuracy
Proposed hypotheses for why the model(s) were inaccurate in the estimates or locations where it was inaccurate.  These reasons should not simply be statements of about the quality of the components of the model, e.g., “the polls were not good” or “economic growth was not a good predictor” but should instead be grounded hypotheses on why components of the model may not have been predictive or may not have been predictive in certain cases.

## Testing these Hypotheses
Proposed quantitative tests that could test these hypotheses, e.g., what data, if available, could allow you to test whether the reason proposed really did cause the inaccuracy in your model.  If there is no plausible test of the hypothesis, explain why.  You do not need to perform these tests or explain them in great detail (e.g., there is no need to write down an equation showing your exact test), just propose them.  

# Looking Forward

Separate national seat share /vote share models

Variables:
### District Level Data
A description of how you might change your model if you were to do it again.  
More district level data, dating much farther back

### Economic Variables
Probably a better economic variable than GDP absolute, which was a weird variable to be honest 

### Expert Ratings
Expert predictions ? 

### Turnout
Turnout variable ! Youth, or indicator for competitive Senate race in that state as proxy for turnout

This blog post may be longer than a typical blog post (remember it accounts for 17.5% of your total grade).  

